version: "3"
services:
#  postgres:
#    image: postgres:9.6
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - 5432:5432
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
     # - ./rule400.yml:/etc/prometheus/rule400.yml
     # - ./rule500.yml:/etc/prometheus/rule500.yml
     # - ./rule-latency.yml:/etc/prometheus/rule-latency.yml
    ports:
      - 9090:9090
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./data:/var/lib/grafana
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=saurabhthemagicman@gmail.com
      - GF_SMTP_PASSWORD=matfwfakwuccunkz
      - GF_SMTP_FROM_ADDRESS=saurabhthemagicman@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Saurabh
    depends_on:
      - prometheus
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
